# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false
warnings_are_errors: false

os:
  - osx
  - linux

r: 
  - devel

r_packages:
  - covr
  - devtools
  - testthat

matrix:
  exclude:
    - r: devel
      os: osx

script:
  - R CMD build --no-build-vignettes --no-manual .
  - test $TRAVIS_R_VERSION_STRING = 'release' && R CMD check --no-build-vignettes --no-manual *tar.gz;
  - test $TRAVIS_R_VERSION_STRING = 'devel' && R CMD check --no-build-vignettes --no-manual --no-tests *tar.gz;

after_success:
  - travis_wait Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
